version: "3.8"
networks:
  # docker network create public
  public:
    external: true
services:
  app:
    build: .
    ports:
      - 3000
    networks:
      - public
      - default
    restart: unless-stopped
# docker-compose.override.yml
# version: "3.8"
# services:
#   app:
#     labels:
#       - "traefik.enable=true"
#       - 'traefik.backend=html-gpt-print'
#       - "traefik.port=3000"
#       - "traefik.frontend.rule=Host:html-gpt-print.deg.mindfine.com"

