version: "3.8"
services:
  app:
    labels:
      - "traefik.enable=true"
      - 'traefik.backend=html-gpt-print'
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:html-gpt-print.deg.mindfine.com"

