version: "3.8"
networks:
  # docker network create public
  public:
    external: true
services:
  app:
    build: .
    ports:
      - 3000
    networks:
      - public
      - default
    restart: unless-stopped
