version: "3.8"
networks:
  # docker network create public
  public:
    external: true
services:
  app:
    build: .
    ports:
      - 3000
    networks:
      - public
      - default
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.html-gpt-print.rule=Host("html-gpt-print.sps.mindfine.com")'
      - "traefik.http.services.html-gpt-print.loadbalancer.server.port=3000"
      - "traefik.http.routers.html-gpt-print.tls.certresolver=myresolver"

